name: Automated Testing

on: [push]

{% raw %}concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true{% endraw %}

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # list of pre-installed softwares is provided here:
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      - name: start mysql server already installed in the image
        run: |
          sudo systemctl start mysql.service
          sudo mysql --version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements**.txt"

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Checking python version
        run: python --version

      - name: Install pre dependencies
        run: |
          sudo apt-get update
          sudo apt install -y build-essential pkg-config python3-dev
          sudo apt-get install libmysqlclient-dev

      - name: Create MySQL user
        run: |
          sudo mysql -uroot -proot -e "create user 'py-user' identified by 'p@@sWord';"
          sudo mysql -uroot -proot -e "grant all privileges on *.* to 'py-user';"

      - name: Verify Mysql connection
        env:
          PORT: 3306
          MYSQL_USER: py-user
          MYSQL_PASSWORD: p@@sWord
          HOST: "127.0.0.1"
        run: mysqladmin ping -h$HOST --port $PORT -u$MYSQL_USER -p$MYSQL_PASSWORD

      - name: Install dependencies from requirements
        run: uv pip install -r requirements/requirements-dev.txt
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run tests
        run: |
          cp .env.sample .env
          python -Wa manage.py test --exclude-tag=external --verbosity=2 --settings={{cookiecutter.project_slug}}.settings.test

